### ISSUE TITLE
Fix weapon blueprint HUD

### ISSUE THREAD

**Issue by Kobakat** [Project-Nova-Team/Project-Nova#100]
When you hold a weapon in your hand, currently the HUD widget is displaying the reticle texture (see bottom right corner of your screen).

To fix this, open each weapon blueprint and find the UI category and change the HUD texture property

![image](https://user-images.githubusercontent.com/54965702/154351398-e5008e81-818c-46d6-938b-82a31cce0561.png)

If you search "T_HUD", the four textures should appear, just apply the appropriate texture to each weapon blueprint

![image](https://user-images.githubusercontent.com/54965702/154351276-0b3c10ab-c25c-4725-a677-7de0fe2903b6.png)

**Comment by Vantrono** [comment]
Done!
